apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - env:
          - name: application_args
            value: >-
              --spring.config.location=file:/home/vishal/tmp/application-dev.properties          
        name: helloworld
        image: vishalsaini21121988/my-first-repo:v4
        volumeMounts:
          - mountPath: /tmp/application-dev.properties/properties
            name: volume-tqzhs
        imagePullPolicy: Always        
      imagePullSecrets:
        - name: regcred
      volumes:
        - configMap:
            name: application-dev.properties
          name: volume-tqzhs
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-lb
  labels:
    app: helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 8085
  selector:
    app: helloworld